name: forma_36_icons
description: Collection of beautiful and well-designed icons from Contentful Forma 36 UI Kit
version: 0.0.1
homepage: https://github.com/hanmajid/forma_36_icons
issue_tracker: https://github.com/hanmajid/forma_36_icons/issues
repository: https://github.com/hanmajid/forma_36_icons
funding:
  - https://github.com/sponsors/hanmajid

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Forma36Icons
      fonts:
        - asset: assets/Forma36Icons.ttf

topics:
  - assets
  - icons
  - ui

screenshots:
  - description: 'Contentful Forma 36 icons'
    path: forma-36-icons.png