// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Forma 36 icons.
///
/// This font was generated by FlutterIcon.com.
class Forma36Icons {
  /// No need for constructor. All properties are static.
  Forma36Icons._();

  /// Forma 36 icons family name.
  static const _kFontFam = 'Forma36Icons';

  /// Forma 36 icons package name.
  static const String? _kFontPkg = 'forma_36_icons';

  /// Icon data for 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrowbackward' glyph.
  static const IconData arrowbackward =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrowforward' glyph.
  static const IconData arrowforward =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrowup' glyph.
  static const IconData arrowup =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'asset' glyph.
  static const IconData asset =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bin' glyph.
  static const IconData bin =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar' glyph.
  static const IconData calendar =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chatbubble' glyph.
  static const IconData chatbubble =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'checkcircle' glyph.
  static const IconData checkcircle =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'checkmark' glyph.
  static const IconData checkmark =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_down' glyph.
  static const IconData chevron_down =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_left' glyph.
  static const IconData chevron_left =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_right' glyph.
  static const IconData chevron_right =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close' glyph.
  static const IconData close =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_up' glyph.
  static const IconData chevron_up =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'code' glyph.
  static const IconData code =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copy' glyph.
  static const IconData copy =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'delete' glyph.
  static const IconData delete =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'download' glyph.
  static const IconData download =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drag' glyph.
  static const IconData drag =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'edit' glyph.
  static const IconData edit =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'entry' glyph.
  static const IconData entry =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cycle' glyph.
  static const IconData cycle =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'error_circle_outline' glyph.
  static const IconData error_circle_outline =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'external_link' glyph.
  static const IconData external_link =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye' glyph.
  static const IconData eye =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'errorcircle' glyph.
  static const IconData errorcircle =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'face_happy' glyph.
  static const IconData face_happy =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_create' glyph.
  static const IconData folder_create =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'filter' glyph.
  static const IconData filter =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_open' glyph.
  static const IconData folder_open =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder' glyph.
  static const IconData folder =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'format_underlined' glyph.
  static const IconData format_underlined =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heading_one' glyph.
  static const IconData heading_one =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heading_two' glyph.
  static const IconData heading_two =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'format_bold' glyph.
  static const IconData format_bold =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heading' glyph.
  static const IconData heading =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'help_circle' glyph.
  static const IconData help_circle =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'horizontal_rule' glyph.
  static const IconData horizontal_rule =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'infocircle' glyph.
  static const IconData infocircle =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list_bulleted' glyph.
  static const IconData list_bulleted =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list_numbered' glyph.
  static const IconData list_numbered =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'loading' glyph.
  static const IconData loading =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'logout' glyph.
  static const IconData logout =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more_horizontal' glyph.
  static const IconData more_horizontal =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus_circle' glyph.
  static const IconData plus_circle =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'format_italic' glyph.
  static const IconData format_italic =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus' glyph.
  static const IconData plus =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'quote' glyph.
  static const IconData quote =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'link' glyph.
  static const IconData link =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more_vertical' glyph.
  static const IconData more_vertical =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'resize' glyph.
  static const IconData resize =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock' glyph.
  static const IconData lock =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more' glyph.
  static const IconData more =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'receipt' glyph.
  static const IconData receipt =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'search' glyph.
  static const IconData search =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'toggle' glyph.
  static const IconData toggle =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star' glyph.
  static const IconData star =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'settings' glyph.
  static const IconData settings =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_down' glyph.
  static const IconData thumb_down =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'text' glyph.
  static const IconData text =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'puzzle' glyph.
  static const IconData puzzle =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shopping_cart' glyph.
  static const IconData shopping_cart =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu' glyph.
  static const IconData menu =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'reference' glyph.
  static const IconData reference =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thumb_up' glyph.
  static const IconData thumb_up =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'triangleoutline' glyph.
  static const IconData triangleoutline =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'warning' glyph.
  static const IconData warning =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'users' glyph.
  static const IconData users =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
